# @package _group_
name: 'icews18'
_target_: examples.datasets.${dataset.name}.ICEWS18Dataset
params:
  seq_len: 10
  follow_batch: ['h_sub', 'h_obj']
  pre_transform:
    - _target_: torch_geometric.nn.models.re_net.RENet.pre_transform
      params:
        seq_len: ${dataset.params.seq_len}
  samplers:
    - stage: 'train'
      sampling: 'dataloader'
    - stage: 'val'
      sampling: 'dataloader'
    - stage: 'test'
      sampling: 'dataloader'
