# @package _group_
name: 'pna'
_target_: examples.models.${model.name}.PNAConvNet
params:
  num_layers: 4
  hidden_channels: 25
  towers: 5
  pre_layers: 1
  post_layers: 1
  divide_input: False
  aggregators: ['mean', 'min', 'max', 'std']
  scalers: ['identity', 'amplification', 'attenuation']
  node_vocab: 21
  edge_vocab: 4
