# @package _group_
_target_: examples.models.pna.PNAConvNet
params:
  towers: 5
  pre_layers: 1
  post_layers: 1
  divide_input: False
  aggregators: ['mean', 'min', 'max', 'std']
  scalers: ['identity', 'amplification', 'attenuation']
  node_vocab: 21
  edge_vocab: 4
